openapi: 3.0.1
info:
  title: "Payment API"
  version: "1.0"

paths:
  /payments:
    post:
      summary: "Create payment"
      operationId: "createPayment"
      requestBody:
        description: "Data of the payment"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Payment"
      responses:
        "201":
          description: "Payment created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentResponse"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: "Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Payment:
      type: object
      required:
        - clientId
        - timestamp
        - amount
      properties:
        clientId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        timestamp:
          type: string
          format: date-time
        amount:
          type: integer
          format: int64
          example: 1

    PaymentResponse:
      type: object
      properties:
        transactionId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"

    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: integer
          example: 400
        message:
          type: string
          example: "Bad request: missing property"
